### ISSUE TITLE
Create dplpy package

### ISSUE THREAD

**Issue by tyson-swetnam** [OpenDendro/dplPy#18]
the main function for calling `dpl` in Python

**Comment by tyson-swetnam** [comment]
In the `dev` branch, I've started creating the necessary files for the `dplpy` python package.

This will allow us to `import dplpy` and to call on the modules within it from the Python console and from notebooks.

**Comment by AndyBunn** [comment]
Excellent.

—-
This device necessitates  brevity

On Oct 31, 2021, at 1:54 PM, Tyson L. Swetnam ***@***.***> wrote:

﻿

In the dev branch, I've started creating the necessary files for the dplpy python package.

This will allow us to import dplpy and to call on the modules within it from the Python console and from notebooks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOpenDendro%2FdplPy%2Fissues%2F18%23issuecomment-955789839&data=04%7C01%7Cbunna%40wwu.edu%7Cfc1d7d7de88f4486e4ca08d99cb09604%7Cdc46140ce26f43efb0ae00f257f478ff%7C0%7C0%7C637713104531997137%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=q70%2FfQoyiJspsi2H7bXlUs%2Fz0rI7lQk0RJ5mWdK%2F9Rw%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAC7UCXKHBBS7T7TXXHVGOJLUJWUHBANCNFSM5HCWHYQA&data=04%7C01%7Cbunna%40wwu.edu%7Cfc1d7d7de88f4486e4ca08d99cb09604%7Cdc46140ce26f43efb0ae00f257f478ff%7C0%7C0%7C637713104531997137%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4k5INu3GuenqbLN2Rd7IDqVnv7Kfp9XveyI6j59qJnE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cbunna%40wwu.edu%7Cfc1d7d7de88f4486e4ca08d99cb09604%7Cdc46140ce26f43efb0ae00f257f478ff%7C0%7C0%7C637713104532007132%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dkRuNrzAj600RkY7r81BJFbny0%2FfamOA%2BJgVbJPZUaY%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cbunna%40wwu.edu%7Cfc1d7d7de88f4486e4ca08d99cb09604%7Cdc46140ce26f43efb0ae00f257f478ff%7C0%7C0%7C637713104532017126%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CF47CvbI7Uqnir4Z5qmvVFdHzTQqKjBwUuaGAZVoi2A%3D&reserved=0>.

**Comment by tyson-swetnam** [comment]
@anushkabande @sajackson314314 you will see where I have created `/src/dplpy.py` on lines 103+ i am calling for `def` files from your respective `summary_tucson.py` `csv_var.py` `tucson_var.py` etc -- you must re-write these to create `def` definitions in each of those .py for their respective module uses, e.g., `read_csv` `read_rwl` `create_json` `create_summary`

**Comment by tyson-swetnam** [comment]
the main `dplpy.py` script is formatted as a `pypi` style project.

**Comment by tyson-swetnam** [comment]
`dplpy.py` is created, and is ready for adding modules (definition funcionts) which are called directly from within `dplpy.py` or are imported from other `.py` files in the `/src` folder. 

Note, that when these are added, they must be documented in the `help` portion of the main `dplpy.py`
