### ISSUE TITLE
Build `read` for dplPy

### ISSUE THREAD

**Issue by tyson-swetnam** [OpenDendro/dplPy#5]
We need to create some read parsers for the Tucson format in Python. 

We can use the R read.tucson format as an example to base our code off

The Tucson format is a text file, there are numerous other CSV and TXT file types which we will also create `read` for.

**Comment by tyson-swetnam** [comment]
https://www.ltrr.arizona.edu/pub/dpl-mac/68k/dpl.txt

**Comment by tyson-swetnam** [comment]
https://www.treeringsociety.org/resources/SOM/Brewer_Murphy_SupplementaryMaterial.pdf

**Comment by kanchukaitis** [comment]
Here are three example Tucson formatted raw (rwl) data files with tree-ring measurements. These are the same 3 that Andy uses for examples in dplR - [rwl.zip](https://github.com/OpenDendro/dplPy/files/6817570/rwl.zip)

**Comment by kanchukaitis** [comment]
http://www.cybis.se/wiki/index.php/Tucson_format

**Comment by kanchukaitis** [comment]
https://www1.ncdc.noaa.gov/pub/data/paleo/treering/treeinfo.txt

**Comment by AndyBunn** [comment]
Ok. I’ve got a lot to say about the Tucson standard. But “say” isn’t exactly le mot juste. Rant? Rage? Sputter incoherently?

We spent more time on getting Tucson files to read than probably any other aspect of dplR. Most of the heavy work is done in C and not in R.
https://github.com/AndyBunn/dplR/blob/master/src/readloop.c

The reason is that IT IS A TERRIBLE FORMAT and DOES NOT FOLLOW A STANDARD. Hear that last part again: there is no standard worth of the name. It doesn’t matter what the TIRDB link is. The standard is not robust. And although the Holmes code will read anything (good!) it fucks with IDs and overwrites series that have duplicate IDs (bad!). This duplicate ID thing happens all the time in people’s rwl files – dplR objects and throws an error code when this happens but the dpl programs read it and don’t tell the user. I hate the Tucson format with the intensity of 10,000 suns.

Perhaps we should have a meeting to discuss?





From: Kevin Anchukaitis ***@***.***>
Reply-To: OpenDendro/dplPy ***@***.***>
Date: Wednesday, July 14, 2021 at 9:29 AM
To: OpenDendro/dplPy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [OpenDendro/dplPy] Build `read` for dplPy (#5)


https://www1.ncdc.noaa.gov/pub/data/paleo/treering/treeinfo.txt<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww1.ncdc.noaa.gov%2Fpub%2Fdata%2Fpaleo%2Ftreering%2Ftreeinfo.txt&data=04%7C01%7Cbunna%40wwu.edu%7C9f160c194a894e69e92e08d946e48664%7Cdc46140ce26f43efb0ae00f257f478ff%7C0%7C0%7C637618769595953145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8kFqJJXO5MpzAaYeWxG6Iqtllt57oSzZWbMdzjbuE8k%3D&reserved=0>

**Comment by kanchukaitis** [comment]
:) - All this being absolutely true, dplPy needs to be able to read Tucson formatted files, ideally as robustly as the Holmes FORTRAN does (but without over-writing duplicate IDs)

**Comment by kanchukaitis** [comment]
Also, it is possible the solution is 'wrap dplR's C code in a Python wrapper' if dplR solved this (as much as it can be solved).

**Comment by AndyBunn** [comment]
Yeah. Absolutely have to be able to read rwl in all its horror. A good test (when ready) is importing the ITRDB and seeing where it chokes. From a design perspective I think it would be nice to have a common codebase that dplR and dplPy can both call for IO. E.g., written in C or python. But maybe this is a down the road thing? But if we have the UGs working now I think we should meet to set priorities. What say you?

From: Kevin Anchukaitis ***@***.***>
Reply-To: OpenDendro/dplPy ***@***.***>
Date: Wednesday, July 14, 2021 at 9:49 AM
To: OpenDendro/dplPy ***@***.***>
Cc: Andy Bunn ***@***.***>, Comment ***@***.***>
Subject: Re: [OpenDendro/dplPy] Build `read` for dplPy (#5)


Also, it is possible the solution is 'wrap dplR's C code in a Python wrapper' if dplR solved this (as much as it can be solved).

**Comment by sajackson314314** [comment]
Hey @tyson-swetnam and @AndyBunn , Anushka and I were having trouble figuring out what the read.ids.r file was reading in. We managed to figure out what the rest of the read files corresponded to but that one eluded us. Do you know what format that's supposed to be?

**Comment by tyson-swetnam** [comment]
> Also, it is possible the solution is 'wrap dplR's C code in a Python wrapper' if dplR solved this (as much as it can be solved).

@anushkabande @sajackson314314 -- there is a C wrapper that calls the R code, we can just call this from Python

**Comment by kanchukaitis** [comment]
@anushkabande @sajackson314314 - 

This is the C code that does the heavy lifting in dplR's read.tucson - https://github.com/AndyBunn/dplR/blob/master/src/readloop.c

**Comment by tyson-swetnam** [comment]
Need to push commits to GitHub for review

**Comment by CosiMichele** [comment]
Working read function has been added to main.
